-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

CREATE TABLE IF NOT EXISTS public.films
(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name character varying(100) NOT NULL,
    description character varying(200),
    release_date date,
    duration integer NOT NULL,
    genre_id integer,
    rating_id integer,
    CONSTRAINT pk_films_film_id PRIMARY KEY (film_id)
);

CREATE TABLE IF NOT EXISTS public.genre
(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name character varying(100) NOT NULL,
    CONSTRAINT genre_genre_name_unq UNIQUE (genre_name)
);

CREATE TABLE IF NOT EXISTS public.rating
(
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_code character varying(10),
    rating_name character varying(200),
    rating_description character varying(500),
    CONSTRAINT rating_rating_code_unq UNIQUE (rating_code)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(512) NOT NULL,
    login character varying(50) NOT NULL,
    user_name character varying(50),
    birthday date,
    CONSTRAINT users_email_unq UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.film_likes
(
    film_id INTEGER,
    user_id INTEGER,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.user_friends
(
    user_id INTEGER,
    friend_id INTEGER,
    confirmed boolean,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS public.film_genres
(
    film_id INTEGER,
    genre_id INTEGER,
    PRIMARY KEY (film_id, genre_id)
);

ALTER TABLE IF EXISTS public.films
DROP CONSTRAINT fk_filmsto_rating;
ALTER TABLE IF EXISTS public.films
    ADD CONSTRAINT fk_filmsto_rating FOREIGN KEY (rating_id)
    REFERENCES public.rating (rating_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.film_likes
DROP CONSTRAINT fk_film_likes_to_films;
ALTER TABLE IF EXISTS public.film_likes
    ADD CONSTRAINT fk_film_likes_to_films FOREIGN KEY (film_id)
    REFERENCES public.films (film_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.film_likes
DROP CONSTRAINT fk_film_likes_to_users;
ALTER TABLE IF EXISTS public.film_likes
    ADD CONSTRAINT fk_film_likes_to_users FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.user_friends
DROP CONSTRAINT fk_user_friends_to_user;
ALTER TABLE IF EXISTS public.user_friends
    ADD CONSTRAINT fk_user_friends_to_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.user_friends
DROP CONSTRAINT fk_user_friends_to_user_as_friend;
ALTER TABLE IF EXISTS public.user_friends
    ADD CONSTRAINT fk_user_friends_to_user_as_friend FOREIGN KEY (friend_id)
    REFERENCES public.users (user_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.film_genres
DROP CONSTRAINT fk_film_genres_to_films;
ALTER TABLE IF EXISTS public.film_genres
    ADD CONSTRAINT fk_film_genres_to_films FOREIGN KEY (film_id)
    REFERENCES public.films (film_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.film_genres
DROP CONSTRAINT fk_film_genres_to_gene;
ALTER TABLE IF EXISTS public.film_genres
    ADD CONSTRAINT fk_film_genres_to_gene FOREIGN KEY (genre_id)
    REFERENCES public.genre (genre_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
